/**
 * The session-document header.
 *
 * These exist because this header already drifted once: the PDF and the .txt
 * each built their own, so the same session exported as
 * "adhd session 1 - akshata / Transcript · <date>" in one format and
 * "Session: adhd session 1 / Generated by Aura" in the other. Both now derive
 * from lib/session-export, and these tests pin the shape so they cannot
 * separate again.
 */

import assert from "node:assert/strict";
import test from "node:test";

import {
  AURA_CREDIT,
  buildSessionTitle,
  buildTextHeader,
} from "../lib/session-export.ts";

const SAMPLE = {
  sessionTitle: "adhd session 1",
  patientName: "akshata",
  kind: "Transcript",
  dateISO: "2026-07-19T23:50:15",
};

function lines(header: string): string[] {
  return header.split("\n");
}

test("title is 'session - patient'", () => {
  assert.equal(buildSessionTitle("adhd session 1", "akshata"), "adhd session 1 - akshata");
});

test("a session with no patient still reads sensibly", () => {
  assert.equal(buildSessionTitle("adhd session 1", null), "adhd session 1 - Unattributed");
  assert.equal(buildSessionTitle("", null), "Untitled session - Unattributed");
});

test("header is title, subtitle, credit rule, then a blank line", () => {
  const [title, subtitle, credit, blank] = lines(buildTextHeader(SAMPLE));
  assert.match(title.trim(), /^adhd session 1 - akshata$/);
  assert.match(subtitle.trim(), /^Transcript · /);
  assert.match(credit, /^-+Generated by Aura-+$/);
  assert.equal(blank, "");
});

test("the credit rule is exactly the block width, with the credit centred", () => {
  const [, , credit] = lines(buildTextHeader(SAMPLE));
  assert.equal(credit.length, 46, "default block width");

  const left = credit.indexOf(AURA_CREDIT);
  const right = credit.length - left - AURA_CREDIT.length;
  // Odd leftovers go to the right, so the two sides differ by at most one.
  assert.ok(Math.abs(left - right) <= 1, `dashes unbalanced: ${left} vs ${right}`);
});

test("title and subtitle are centred against the rule", () => {
  const [title, subtitle, credit] = lines(buildTextHeader(SAMPLE));
  for (const line of [title, subtitle]) {
    const lead = line.length - line.trimStart().length;
    const trail = credit.length - line.length;
    assert.ok(
      Math.abs(lead - trail) <= 1,
      `"${line.trim()}" is not centred (lead ${lead}, trail ${trail})`,
    );
  }
});

test("a long title widens the rule instead of overflowing it", () => {
  const long = "a very long session title that comfortably exceeds the default width";
  const [title, , credit] = lines(
    buildTextHeader({ ...SAMPLE, sessionTitle: long }),
  );
  assert.ok(credit.length > 46, "rule should grow");
  assert.ok(credit.length >= title.length, "rule must not be shorter than the title");
});

test("the body starts on its own line after the header", () => {
  const header = buildTextHeader(SAMPLE);
  const doc = header + "Therapist: hello.";
  assert.ok(doc.endsWith("\n\nTherapist: hello."), "one blank line before the body");
});
