/**
 * Client-side PDF export for session artifacts (transcript / summary).
 * Every document is titled "<Session title> - <Patient name>" per the product
 * spec, with a kind + date subtitle. Pure jsPDF text layout — no fonts or
 * assets to fetch, so it works fully offline.
 */

import { jsPDF } from "jspdf";

import {
  AURA_CREDIT,
  buildSessionSubtitle,
  buildSessionTitle,
} from "@/lib/session-export";

// Re-exported so callers that already import it from here keep working; the
// definition lives in session-export.ts, shared with the .txt export.
export { buildSessionTitle };

export interface PdfSection {
  heading?: string;
  body: string;
}

function slug(s: string): string {
  return (
    s
      .replace(/[^a-z0-9]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase() || "session"
  );
}

export function downloadSessionPdf(opts: {
  sessionTitle: string;
  patientName: string | null;
  kind: string; // "Transcript" | "Summary"
  dateISO: string;
  sections: PdfSection[];
}): void {
  const { sessionTitle, patientName, kind, dateISO, sections } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const margin = 56;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensure = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Title — "Session title - Patient name"
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(30, 40, 45);
  const titleLines = doc.splitTextToSize(
    buildSessionTitle(sessionTitle, patientName),
    maxW,
  );
  doc.text(titleLines, pageW / 2, y, { align: "center" });
  y += titleLines.length * 22 + 2;

  // Subtitle — kind · date
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(120, 130, 135);
  doc.text(buildSessionSubtitle(kind, dateISO), pageW / 2, y, {
    align: "center",
  });
  y += 18;

  // The credit sits on the rule, mirroring the dashed
  // "------Generated by Aura------" line in the .txt export.
  doc.setFontSize(9);
  doc.setTextColor(150, 158, 162);
  const creditW = doc.getTextWidth(AURA_CREDIT);
  const gap = 10;
  doc.text(AURA_CREDIT, pageW / 2, y, { align: "center" });
  doc.setDrawColor(205, 214, 210);
  const ruleY = y - 3;
  doc.line(margin, ruleY, pageW / 2 - creditW / 2 - gap, ruleY);
  doc.line(pageW / 2 + creditW / 2 + gap, ruleY, pageW - margin, ruleY);
  y += 24;

  for (const section of sections) {
    if (section.heading) {
      ensure(26);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(40, 90, 80);
      doc.text(section.heading, margin, y);
      y += 18;
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(35, 45, 50);
    const lines = doc.splitTextToSize(section.body?.trim() || "—", maxW);
    for (const line of lines) {
      ensure(16);
      doc.text(line, margin, y);
      y += 15;
    }
    y += 12;
  }

  doc.save(`${slug(sessionTitle)}-${slug(kind)}.pdf`);
}
