/**
 * The one definition of a session document's header.
 *
 * The PDF and the .txt had each built their own, so they drifted: the PDF said
 * "adhd session 1 - akshata / Transcript · <date>" while the .txt said
 * "Session: adhd session 1 / Generated by Aura". Both formats now derive from
 * the functions here, so changing the header changes it everywhere.
 *
 * Canonical shape, centred:
 *
 *              adhd session 1 - akshata
 *        Transcript · 19/7/2026, 11:50:15 PM
 *   ------------Generated by Aura------------------
 */

export const AURA_CREDIT = "Generated by Aura";

/** Minimum width of the plain-text header block, in characters. */
const MIN_TEXT_WIDTH = 46;

/** "Session title - Patient name", the document's first line. */
export function buildSessionTitle(
  sessionTitle: string,
  patientName: string | null,
): string {
  return `${sessionTitle || "Untitled session"} - ${patientName ?? "Unattributed"}`;
}

/** "Transcript · 19/7/2026, 11:50:15 PM" — what the document is, and when. */
export function buildSessionSubtitle(kind: string, dateISO: string): string {
  return `${kind} · ${new Date(dateISO).toLocaleString()}`;
}

function centre(text: string, width: number): string {
  return " ".repeat(Math.max(0, Math.floor((width - text.length) / 2))) + text;
}

/** The credit rule: dashes with the credit centred inside them. */
function creditRule(width: number): string {
  const dashes = Math.max(0, width - AURA_CREDIT.length);
  const left = Math.floor(dashes / 2);
  return "-".repeat(left) + AURA_CREDIT + "-".repeat(dashes - left);
}

/**
 * The header for a plain-text export, centred with spaces and ending in a
 * blank line. Monospace is not guaranteed in a .txt viewer, so this centres on
 * character count — the usual convention, and it lines up in any fixed-width
 * font.
 */
export function buildTextHeader(opts: {
  sessionTitle: string;
  patientName: string | null;
  kind: string;
  dateISO: string;
}): string {
  const title = buildSessionTitle(opts.sessionTitle, opts.patientName);
  const subtitle = buildSessionSubtitle(opts.kind, opts.dateISO);
  const width = Math.max(MIN_TEXT_WIDTH, title.length, subtitle.length);

  return [centre(title, width), centre(subtitle, width), creditRule(width), "", ""].join(
    "\n",
  );
}
