"use client";

/**
 * Full transcript beside its structured summary. The transcript can be
 * downloaded as a .txt file; the summary is generated on demand by a local
 * model (Ollama, with a heuristic fallback) and persisted server-side.
 */

import { useState } from "react";
import { Download, Loader2, Sparkles, User } from "lucide-react";

import { summarizeSession } from "@/lib/api";
import { toast } from "@/lib/toast";
import type { SessionSummary } from "@/lib/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "session";
}

export function TranscriptPanel({
  sessionId,
  title,
  transcript,
  initialSummary,
}: {
  sessionId: string;
  title: string;
  transcript: string;
  initialSummary: SessionSummary | null;
}) {
  const [summary, setSummary] = useState<SessionSummary | null>(initialSummary);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function downloadTxt() {
    const header = `Session: ${title}\nGenerated by Aura\n${"=".repeat(40)}\n\n`;
    const blob = new Blob([header + transcript], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${slugify(title)}-transcript.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Transcript downloaded");
  }

  async function summarize() {
    setBusy(true);
    setError(null);
    try {
      setSummary(await summarizeSession(sessionId));
      toast.success("Summary ready");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not summarize.");
    } finally {
      setBusy(false);
    }
  }

  const details: { label: string; value: string }[] = summary
    ? [
        { label: "Name", value: summary.patient_name },
        { label: "Age", value: summary.age },
        { label: "Details", value: summary.personal_details },
      ].filter((d) => d.value.trim())
    : [];

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      {/* Transcript */}
      <div className="glass rounded-2xl p-6">
        <div className="mb-3 flex items-center justify-between gap-2">
          <h3 className="font-display text-sm font-semibold uppercase tracking-wide text-muted-foreground">
            Full transcript
          </h3>
          <Button variant="secondary" size="sm" onClick={downloadTxt}>
            <Download />
            Download .txt
          </Button>
        </div>
        <p className="max-h-96 overflow-y-auto whitespace-pre-wrap text-sm leading-relaxed text-foreground/85">
          {transcript}
        </p>
      </div>

      {/* Summary */}
      <div className="glass rounded-2xl p-6">
        <div className="mb-3 flex items-center justify-between gap-2">
          <h3 className="font-display text-sm font-semibold uppercase tracking-wide text-muted-foreground">
            Summary
          </h3>
          <Button size="sm" onClick={summarize} disabled={busy}>
            {busy ? <Loader2 className="animate-spin" /> : <Sparkles />}
            {summary ? "Regenerate" : "Summarize"}
          </Button>
        </div>

        {error && (
          <p role="alert" className="text-sm text-destructive">
            {error}
          </p>
        )}

        {!summary && !busy && !error && (
          <p className="text-sm text-muted-foreground">
            Generate a structured summary — patient details and what was
            discussed — from the transcript. Runs locally on your machine.
          </p>
        )}

        {busy && !summary && (
          <p className="text-sm text-muted-foreground">
            Summarizing on-device… this can take a moment.
          </p>
        )}

        {summary && (
          <div className="space-y-4">
            {details.length > 0 ? (
              <div className="rounded-xl border border-border bg-foreground/[0.03] p-4">
                <div className="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  <User className="size-3.5" />
                  Patient details
                </div>
                <dl className="space-y-1 text-sm">
                  {details.map((d) => (
                    <div key={d.label} className="flex gap-2">
                      <dt className="w-16 shrink-0 text-muted-foreground">
                        {d.label}
                      </dt>
                      <dd className="text-foreground/90">{d.value}</dd>
                    </div>
                  ))}
                </dl>
              </div>
            ) : (
              <p className="text-xs text-muted-foreground">
                No explicit patient details were stated in the transcript.
              </p>
            )}

            <div>
              <p className="mb-1 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Discussion
              </p>
              <p className="text-sm leading-relaxed text-foreground/90">
                {summary.discussion || "—"}
              </p>
            </div>

            <Badge tone={summary.engine === "ollama" ? "accent" : "muted"}>
              {summary.engine === "ollama" ? "Local LLM" : "Heuristic"}
            </Badge>
          </div>
        )}
      </div>
    </div>
  );
}
